version: 0.2

phases:
    install:
        commands:
            - npm install -g serverless
            - npm install serverless-domain-manager serverless-plugin-git-variables --no-save
            - mkdir -p layers/nodejs
            - cp package*.json layers/nodejs
            - npm install --prefix layers/nodejs
    pre_build:
        commands:
            - cp src/* ./
    build:
        commands:
            - serverless deploy
