version: 0.2

phases:
    install:
        commands:
            - npm install -g serverless
            - npm install serverless-domain-manager serverless-plugin-git-variables --no-save
            - mkdir -p layer/nodejs
            - cp package*.json layer/nodejs
            - npm install --prefix layer/nodejs
    pre_build:
        commands:
            - cp src/* ./
    build:
        commands:
            - serverless deploy
