version: 0.2

phases:
    install:
        commands:
            - npm i --quiet
            - mv ./node_modules ./functions/node_modules

artifacts:
    files:
        - '**/*'
    discard-paths: no
    base-directory: functions
