version: 0.2

phases:
    install:
        commands:
            - mkdir -p layers/nodejs
            - cp package*.json layers/nodejs
            - npm install
            - npm install --production --prefix layers/nodejs
    pre_build:
        commands:
            - cp -r src/* ./
    build:
        commands:
            - npx serverless deploy
