service: entu-api

provider:
    name: aws
    runtime: nodejs10.x
    stage: prod
    stackName: ${self:service}
    apiName: ${self:service}
    region: eu-central-1
    endpointType: regional
    memorySize: 256
    timeout: 30
    logRetentionInDays: 30

    apiGateway:
        minimumCompressionSize: 32

    iamRoleStatements:
        -
            Effect: Allow
            Action:
                - s3:GetObject
                - s3:GetObjectAcl
            Resource: arn:aws:s3:::${ssm:/entu-api-files-s3-bucket~true}/*
        -
            Effect: Allow
            Action:
                - xray:PutTraceSegments
                - xray:PutTelemetryRecords
            Resource: '*'
        -
            Effect: Allow
            Action:
                - sqs:SendMessage
                - sqs:GetQueueUrl
            Resource: ${ssm:/entu-api-entity-aggregate-queue~true}
        -
            Effect: Allow
            Action: sqs:ListQueues
            Resource: arn:aws:sqs:${self:provider.region}:*:*
        -
            Effect: Allow
            Action: ssm:GetParameter
            Resource: arn:aws:ssm:${self:provider.region}:*:*

    deploymentBucket:
        name: ${self:service}
        serverSideEncryption: AES256

    environment:
        GIT_BRANCH: ${git:branch}
        GIT_SHA1: ${git:sha1}

    vpc:
        securityGroupIds:
            - ${ssm:/entu-api-vpc-security-group-1~true}
        subnetIds:
            - ${ssm:/entu-api-vpc-subnet-1~true}
            - ${ssm:/entu-api-vpc-subnet-2~true}
            - ${ssm:/entu-api-vpc-subnet-3~true}

package:
    individually: true
    exclude:
        - '.*/**'
    include:
        - _helpers.js

functions:
    account-get:
        handler: account/get.handler
        name: ${self:service}-account-get
        description: Returns account info and usage statistics
        package:
            include:
                - account/get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /account
                    method: get
                    cors: true

    auth-get:
        handler: auth/get.handler
        name: ${self:service}-auth-get
        description: Authenticates user by API key
        package:
            include:
                - auth/get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /auth
                    method: get
                    cors: true

    auth-apple-get:
        handler: auth/apple.handler
        name: ${self:service}-auth-apple-get
        description: Redirects user to auth in Apple
        package:
            include:
                - auth/apple.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /auth/apple
                    method: get

    auth-google-get:
        handler: auth/google.handler
        name: ${self:service}-auth-google-get
        description: Redirects user to auth in Google
        package:
            include:
                - auth/google.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /auth/google
                    method: get

    auth-lhv-get:
        handler: auth/lhv-get.handler
        name: ${self:service}-auth-lhv-get
        description: Get LHV banklink form url and signed data
        package:
            include:
                - auth/lhv-get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /auth/lhv
                    method: get

    auth-lhv-post:
        handler: auth/lhv-post.handler
        name: ${self:service}-auth-lhv-post
        description: Handles POST request from LHV banklink
        package:
            include:
                - auth/lhv-post.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /auth/lhv
                    method: post

    entities-get:
        handler: entity/entities-get.handler
        name: ${self:service}-entities-get
        description: Get list of entities
        package:
            include:
                - entity/entities-get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /entity
                    method: get
                    cors: true

    entity-get:
        handler: entity/get.handler
        name: ${self:service}-entity-get
        description: Get one entity with given id
        package:
            include:
                - entity/get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /entity/{id}
                    method: get
                    cors: true

    entity-post:
        handler: entity/post.handler
        name: ${self:service}-entity-post
        description: Add new properties to entity
        package:
            include:
                - entity/post.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /entity
                    method: post
                    cors: true
            -
                http:
                    path: /entity/{id}
                    method: post
                    cors: true

    entity-delete:
        handler: entity/delete.handler
        name: ${self:service}-entity-delete
        description: Delete entity with given id
        package:
            include:
                - entity/delete.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /entity/{id}
                    method: delete
                    cors: true

    entity-aggregate:
        handler: entity/aggregate.handler
        name: ${self:service}-entity-aggregate
        description: Aggregate entity with given id
        package:
            include:
                - entity/aggregate.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        reservedConcurrency: 10
        events:
            -
                sqs:
                    arn: ${ssm:/entu-api-entity-aggregate-queue~true}
                    batchSize: 1

    property-get:
        handler: property/get.handler
        name: ${self:service}-property-get
        description: Get property with given id
        package:
            include:
                - property/get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /property/{id}
                    method: get
                    cors: true

    property-delete:
        handler: property/delete.handler
        name: ${self:service}-property-delete
        description: Delete property with given id
        package:
            include:
                - property/delete.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /property/{id}
                    method: delete
                    cors: true

layers:
    commonNodeLibs:
        path: layers
        compatibleRuntimes:
            - nodejs10.x

# resources:
#     Resources:
#         entityAggregateQueue:
#             Type: AWS::SQS::Queue
#             Properties:
#                 QueueName: entu-api-entity-aggregate-queue
#         entuFilesS3:
#             Type: AWS::S3::Bucket
#             Properties:
#                 BucketName: ${ssm:/entu-api-files-s3-bucket~true}

plugins:
    - serverless-domain-manager
    - serverless-plugin-git-variables

custom:
    exportGitVariables: false
    customDomain:
        domainName: ${ssm:/entu-api-domain~true}
        basePath: ''
        stage: ${self:provider.stage}
        createRoute53Record: false
        endpointType: regional
