service: entu-api

provider:
    name: aws
    runtime: nodejs8.10
    stage: prod
    stackName: ${self:service}
    apiName: ${self:service}
    region: eu-central-1
    endpointType: regional
    memorySize: 256
    timeout: 30
    logRetentionInDays: 30

    iamRoleStatements:
        -
            Effect: Allow
            Action:
                - s3:GetObject
                - s3:GetObjectAcl
            Resource: arn:aws:s3:::${ssm:/entu-api-files-s3-bucket~true}/*
        -
            Effect: Allow
            Action:
                - xray:PutTraceSegments
                - xray:PutTelemetryRecords
            Resource: '*'
        -
            Effect: Allow
            Action:
                - sqs:SendMessage
                - sqs:GetQueueUrl
            Resource: ${ssm:/entu-api-entity-aggregate-queue~true}
        -
            Effect: Allow
            Action:
                - sqs:ListQueues
            Resource: arn:aws:sqs:${self:provider.region}:*:*

    deploymentBucket:
        name: ${self:service}
        serverSideEncryption: AES256

    environment:
        GIT_BRANCH: ${git:branch}
        GIT_SHA1: ${git:sha1}
        JWT_SECRET: ${ssm:/entu-api-jwt-secret~true}

    vpc:
        securityGroupIds:
            - ${ssm:/entu-api-vpc-security-group-1~true}
        subnetIds:
            - ${ssm:/entu-api-vpc-subnet-1~true}
            - ${ssm:/entu-api-vpc-subnet-2~true}
            - ${ssm:/entu-api-vpc-subnet-3~true}

package:
    individually: true
    exclude:
        - src/**
        - layers/**
        - node_modules/**
        - '*'
    include:
        - _helpers.js

functions:
    account-get:
        handler: account-get.handler
        name: ${self:service}-account-get
        description: Returns account info and usage statistics
        package:
            include:
                - account-get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /account
                    method: get
                    cors: true

    auth-get:
        handler: auth-get.handler
        name: ${self:service}-auth-get
        description: Authenticates user by API key
        package:
            include:
                - auth-get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /auth
                    method: get
                    cors: true

    auth-google-get:
        handler: auth-google-get.handler
        name: ${self:service}-auth-google-get
        description: Redirects user to auth in Google
        package:
            include:
                - auth-google-get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /auth/google
                    method: get
        environment:
            GOOGLE_ID: ${ssm:/entu-api-google-id~true}
            GOOGLE_SECRET: ${ssm:/entu-api-google-secret~true}

    auth-facebook-get:
        handler: auth-facebook-get.handler
        name: ${self:service}-auth-facebook-get
        description: Redirects user to auth in Facebook
        package:
            include:
                - auth-facebook-get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /auth/facebook
                    method: get
        environment:
            FACEBOOK_ID: ${ssm:/entu-api-facebook-id~true}
            FACEBOOK_SECRET: ${ssm:/entu-api-facebook-secret~true}

    auth-microsoft-get:
        handler: auth-microsoft-get.handler
        name: ${self:service}-auth-microsoft-get
        description: Redirects user to auth in Microsoft
        package:
            include:
                - auth-microsoft-get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /auth/microsoft
                    method: get
        environment:
            MICROSOFT_ID: ${ssm:/entu-api-microsoft-id~true}
            MICROSOFT_SECRET: ${ssm:/entu-api-microsoft-secret~true}

    entities-get:
        handler: entities-get.handler
        name: ${self:service}-entities-get
        description: Get list of entities
        package:
            include:
                - entities-get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /entity
                    method: get
                    cors: true
        environment:
            S3_BUCKET: ${ssm:/entu-api-files-s3-bucket~true}
            S3_ENDPOINT: ${ssm:/entu-api-files-s3-endpoint~true}

    entity-get:
        handler: entity-get.handler
        name: ${self:service}-entity-get
        description: Get one entity with given id
        package:
            include:
                - entity-get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /entity/{id}
                    method: get
                    cors: true
        environment:
            S3_BUCKET: ${ssm:/entu-api-files-s3-bucket~true}
            S3_ENDPOINT: ${ssm:/entu-api-files-s3-endpoint~true}

    entity-post:
        handler: entity-post.handler
        name: ${self:service}-entity-post
        description: Add new properties to entity
        package:
            include:
                - entity-post.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /entity
                    method: post
                    cors: true
            -
                http:
                    path: /entity/{id}
                    method: post
                    cors: true
        environment:
            S3_BUCKET: ${ssm:/entu-api-files-s3-bucket~true}

    entity-delete:
        handler: entity-delete.handler
        name: ${self:service}-entity-delete
        description: Delete entity with given id
        package:
            include:
                - entity-delete.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /entity/{id}
                    method: delete
                    cors: true

    entity-aggregate:
        handler: entity-aggregate.handler
        name: ${self:service}-entity-aggregate
        description: Aggregate entity with given id
        package:
            include:
                - entity-aggregate.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        reservedConcurrency: 10
        events:
            -
                sqs:
                    arn: ${ssm:/entu-api-entity-aggregate-queue~true}
                    batchSize: 1

    property-get:
        handler: property-get.handler
        name: ${self:service}-property-get
        description: Get property with given id
        package:
            include:
                - property-get.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /property/{id}
                    method: get
                    cors: true
        environment:
            S3_BUCKET: ${ssm:/entu-api-files-s3-bucket~true}
            S3_ENDPOINT: ${ssm:/entu-api-files-s3-endpoint~true}

    property-delete:
        handler: property-delete.handler
        name: ${self:service}-property-delete
        description: Delete property with given id
        package:
            include:
                - property-delete.js
        layers:
            - {Ref: CommonNodeLibsLambdaLayer}
        events:
            -
                http:
                    path: /property/{id}
                    method: delete
                    cors: true

layers:
    commonNodeLibs:
        path: layers
        compatibleRuntimes:
            - nodejs8.10

# resources:
#     Resources:
#         entityAggregateQueue:
#             Type: AWS::SQS::Queue
#             Properties:
#                 QueueName: entu-api-entity-aggregate-queue
#         entuFilesS3:
#             Type: AWS::S3::Bucket
#             Properties:
#                 BucketName: ${ssm:/entu-api-files-s3-bucket~true}

plugins:
    - serverless-domain-manager
    - serverless-plugin-git-variables

custom:
    customDomain:
        domainName: ${ssm:/entu-api-domain~true}
        basePath: ''
        stage: ${self:provider.stage}
        createRoute53Record: false
        endpointType: regional
